#!/bin/sh
#
# ckatsak, Tue Nov 11 04:59:29 PM EET 2025

/bin/mount -v -t tmpfs -o noatime,mode=0755 tmpfs /overlay
mkdir -vp /overlay/root /overlay/work

/bin/mount -v \
	-o noatime,lowerdir=/,upperdir=/overlay/root,workdir=/overlay/work \
	-t overlay "fbpml-overlay:/overlay/root" /mnt
pivot_root /mnt /mnt/rom

exec /sbin/init $@

